#!/bin/sh
#
# @name Zeppelin NT-07 (ZLT-NT)
# @type Airship
# @class Airship
#
# PteroSim/JSBSim ZLT-NT allocation in PX4 body coordinates
# (X forward, Y right, Z down; origin at the vehicle CG).
#
# HIL actuator order is explicit and matches Controls.xml:
# Motor1 = starboard forward, Motor2 = port forward,
# Motor3 = aft forward, Motor4 = lateral yaw.
#

. ${R}etc/init.d/rc.airship_defaults

param set-default COM_PREARM_MODE 2
param set-default COM_RC_IN_MODE 1

param set-default CA_AIRFRAME 9
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_AX 1
param set-default CA_ROTOR0_AZ 0
param set-default CA_ROTOR0_KM 0
param set-default CA_ROTOR0_PX 12.0
param set-default CA_ROTOR0_PY 8.6
param set-default CA_ROTOR0_PZ 3.5

param set-default CA_ROTOR1_AX 1
param set-default CA_ROTOR1_AZ 0
param set-default CA_ROTOR1_KM 0
param set-default CA_ROTOR1_PX 12.0
param set-default CA_ROTOR1_PY -8.6
param set-default CA_ROTOR1_PZ 3.5

param set-default CA_ROTOR2_AX 1
param set-default CA_ROTOR2_AZ 0
param set-default CA_ROTOR2_KM 0
param set-default CA_ROTOR2_PX -37.4

param set-default CA_ROTOR3_AY -1
param set-default CA_ROTOR3_AZ 0
param set-default CA_ROTOR3_KM 0
param set-default CA_ROTOR3_PX -36.1
param set-default CA_ROTOR3_PY -1.1
param set-default CA_ROTOR3_PZ -0.2

# HIL_ACTUATOR_CONTROLS uses these actuator-output slots.
param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

# Only the lateral yaw thruster is reversible.
param set-default CA_R_REV 8
