#!/bin/sh
#
# @name F450
# @type Multicopter
#
# Written from this vehicle's own files, in its engine order, so the channel a motor takes here is
# the channel Controls.xml gives it. Geometry is Propulsion.xml turned from JSBSim's structural frame
# (X aft, Y right, Z up) into PX4's allocation frame (forward, right, down); the CG is at the origin
# (Mass.xml), so the two share one centre. KM follows <sense>, which is what tells the allocator which
# rotor fights which in yaw. CT is the thrust this simulation actually makes, solved from the motor
# and propeller definitions at the speed they balance -- 10506 rpm, 15.7 N a rotor -- and not from a
# datasheet, because it is the simulation the allocator has to match.
#

. ${R}etc/init.d/rc.mc_defaults

param set-default CA_AIRFRAME 0
param set-default MAV_TYPE 2

param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.1651
param set-default CA_ROTOR0_PY 0.1651
param set-default CA_ROTOR0_PZ -0.025
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR0_CT 15.72
param set-default CA_ROTOR1_PX -0.1651
param set-default CA_ROTOR1_PY -0.1651
param set-default CA_ROTOR1_PZ -0.025
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR1_CT 15.72
param set-default CA_ROTOR2_PX 0.1651
param set-default CA_ROTOR2_PY -0.1651
param set-default CA_ROTOR2_PZ -0.025
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR2_CT 15.72
param set-default CA_ROTOR3_PX -0.1651
param set-default CA_ROTOR3_PY 0.1651
param set-default CA_ROTOR3_PZ -0.025
param set-default CA_ROTOR3_KM -0.05
param set-default CA_ROTOR3_CT 15.72

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

param set-default SIM_BAT_ENABLE 0
param set-default COM_ARM_CHK_ESCS 0
param set-default SYS_HAS_NUM_ASPD 0
